sudo: required

dist: xenial

# This moves Kubernetes specific config files.
env:
  global:
    - KIND_VERSION=v0.9.0
    - KUBECTL_VERSION=v1.19.0
    - KIND_KUBE_1_15=kindest/node:v1.15.12@sha256:d9b939055c1e852fe3d86955ee24976cab46cba518abcb8b13ba70917e6547a6
    - KIND_KUBE_1_16=kindest/node:v1.16.15@sha256:a89c771f7de234e6547d43695c7ab047809ffc71a0c3b65aa54eda051c45ed20
    - KIND_KUBE_1_17=kindest/node:v1.17.11@sha256:5240a7a2c34bf241afb54ac05669f8a46661912eab05705d660971eeb12f6555
    - KIND_KUBE_1_18=kindest/node:v1.18.8@sha256:f4bcc97a0ad6e7abaf3f643d890add7efe6ee4ab90baeb374b4f41a4c95567eb
    - KIND_KUBE_1_19=kindest/node:v1.19.1@sha256:98cf5288864662e37115e362b23e4369c8c4a408f99cbc06e58ac30ddc721600

language: go
go:
  - 1.13.x

services:
  - docker

jobs:
  include:
    - env: KIND_NODE_IMAGE=$KIND_KUBE_1_15
      name: "Deploy helm charts on Kubernetes 1.15"

    - env: KIND_NODE_IMAGE=$KIND_KUBE_1_16
      name: "Deploy helm charts on Kubernetes 1.16"

    - env: KIND_NODE_IMAGE=$KIND_KUBE_1_17
      name: "Deploy helm charts on Kubernetes 1.17"

    - env: KIND_NODE_IMAGE=$KIND_KUBE_1_18
      name: "Deploy helm charts on Kubernetes 1.18"

    - env: KIND_NODE_IMAGE=$KIND_KUBE_1_19
      name: "Deploy helm charts on Kubernetes 1.19"


before_script:
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$KUBECTL_VERSION/bin/linux/amd64/kubectl
  - chmod +x ./kubectl && sudo mv ./kubectl /usr/local/bin/kubectl
  - curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
  - chmod 700 get_helm.sh
  - ./get_helm.sh
  - curl https://raw.githubusercontent.com/zlabjp/kubernetes-scripts/master/wait-until-pods-ready > wait_until_pods_ready.sh
  - chmod +x wait_until_pods_ready.sh
  - GO111MODULE="on" go get sigs.k8s.io/kind@$KIND_VERSION && kind create cluster --image $KIND_NODE_IMAGE

script:
  - kubectl cluster-info
  - helm template travis-test-2 . --set limits.cpu=1000m --set limits.workers=1 --set limits.gpu=0 | kubectl apply --validate -f -
  - sleep 2
  - ./wait_until_pods_ready.sh 30 2