apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: {{ template "mlbench.name" . }}
    component: "{{ .Values.master.name }}"
    chart: {{ template "mlbench.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "mlbench.master.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "mlbench.master.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "mlbench.master.fullname" . }}
  namespace: {{ .Release.Namespace }}