{{ if .Values.weave.enabled }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: weave-net
  annotations:
  cloud.weave.works/launcher-info: |-
    {
    "original-request": {
      "url": "/k8s/v1.10/net.yaml?k8s-version=1.11",
      "date": "Tue Aug 21 2018 07:41:54 GMT+0000 (UTC)"
    },
    "email-address": "support@weave.works"
    }
  labels:
rules:
- apiGroups:
  - ''
  resources:
  - pods
  - namespaces
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ''
  resources:
  - nodes/status
  verbs:
  - patch
  - update
{{ end }}