{{ if .Values.weave.enabled }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: weave-net
  annotations:
  cloud.weave.works/launcher-info: |-
    {
    "original-request": {
      "url": "/k8s/v1.10/net.yaml?k8s-version=1.11",
      "date": "Tue Aug 21 2018 07:41:54 GMT+0000 (UTC)"
    },
    "email-address": "support@weave.works"
    }
  labels:
  namespace: kube-system
rules:
- apiGroups: [""]
  resourceNames: ["weave-net"]
  resources: ["configmaps"]
  verbs: ["get", "update"]
- apiGroups: ['']
  resources: ["configmaps"]
  verbs: ["create"]
{{ end }}