name: mlbench-helm

on: [push]

env:
  KIND_VERSION: v0.9.0
  KUBECTL_VERSION: v1.19.0
jobs:
  kubernetes-1-15:
      name: "Deploy helm charts on Kubernetes 1.15"
      runs-on: ubuntu-latest
      env:
        KIND_NODE_IMAGE: kindest/node:v1.15.12@sha256:d9b939055c1e852fe3d86955ee24976cab46cba518abcb8b13ba70917e6547a6
      steps:
        - uses: actions/checkout@master
        - uses: actions/setup-go@v2
          with:
            stable: 'false'
            go-version: '1.13.x' # The Go version to download (if necessary) and use.
        - run: chmod +x ./run-tests.sh && ./run-tests.sh

  kubernetes-1-16:
      name: "Deploy helm charts on Kubernetes 1.16"
      runs-on: ubuntu-latest
      env:
        KIND_NODE_IMAGE: kindest/node:v1.16.15@sha256:a89c771f7de234e6547d43695c7ab047809ffc71a0c3b65aa54eda051c45ed20
      steps:
        - uses: actions/checkout@master
        - uses: actions/setup-go@v2
          with:
            stable: 'false'
            go-version: '1.13.x' # The Go version to download (if necessary) and use.
        - run: chmod +x ./run-tests.sh && ./run-tests.sh

  kubernetes-1-17:
    name: "Deploy helm charts on Kubernetes 1.17"
    runs-on: ubuntu-latest
    env:
      KIND_NODE_IMAGE: kindest/node:v1.17.11@sha256:5240a7a2c34bf241afb54ac05669f8a46661912eab05705d660971eeb12f6555
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.13.x' # The Go version to download (if necessary) and use.
      - run: chmod +x ./run-tests.sh && ./run-tests.sh

  kubernetes-1-18:
    name: "Deploy helm charts on Kubernetes 1.18"
    runs-on: ubuntu-latest
    env:
      KIND_NODE_IMAGE: kindest/node:v1.18.8@sha256:f4bcc97a0ad6e7abaf3f643d890add7efe6ee4ab90baeb374b4f41a4c95567eb
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.13.x' # The Go version to download (if necessary) and use.
      - run: chmod +x ./run-tests.sh && ./run-tests.sh

  kubernetes-1-19:
    name: "Deploy helm charts on Kubernetes 1.19"
    runs-on: ubuntu-latest
    env:
      KIND_NODE_IMAGE: kindest/node:v1.19.1@sha256:98cf5288864662e37115e362b23e4369c8c4a408f99cbc06e58ac30ddc721600
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.13.x' # The Go version to download (if necessary) and use.
      - run: chmod +x ./run-tests.sh && ./run-tests.sh